
package com.audit.modules.system.entity;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContractQueryRun", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.101.11.247/ElectricityAuditContractQuery/ContractQuery.svc?wsdl")
public class ContractQueryRun
    extends Service
{

    private final static URL CONTRACTQUERYRUN_WSDL_LOCATION;
    private final static WebServiceException CONTRACTQUERYRUN_EXCEPTION;
    private final static QName CONTRACTQUERYRUN_QNAME = new QName("http://tempuri.org/", "ContractQueryRun");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.101.11.245/ElectricityAuditContractQuery/ContractQuery.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTRACTQUERYRUN_WSDL_LOCATION = url;
        CONTRACTQUERYRUN_EXCEPTION = e;
    }

    public ContractQueryRun() {
        super(__getWsdlLocation(), CONTRACTQUERYRUN_QNAME);
    }

    public ContractQueryRun(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTRACTQUERYRUN_QNAME, features);
    }

    public ContractQueryRun(URL wsdlLocation) {
        super(wsdlLocation, CONTRACTQUERYRUN_QNAME);
    }

    public ContractQueryRun(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTRACTQUERYRUN_QNAME, features);
    }

    public ContractQueryRun(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContractQueryRun(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IContractQuery
     */
    @WebEndpoint(name = "BasicHttpBinding_IContractQuery")
    public IContractQuery getBasicHttpBindingIContractQuery() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IContractQuery"), IContractQuery.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IContractQuery
     */
    @WebEndpoint(name = "BasicHttpBinding_IContractQuery")
    public IContractQuery getBasicHttpBindingIContractQuery(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IContractQuery"), IContractQuery.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTRACTQUERYRUN_EXCEPTION!= null) {
            throw CONTRACTQUERYRUN_EXCEPTION;
        }
        return CONTRACTQUERYRUN_WSDL_LOCATION;
    }

}
